# Generated by Django 3.0a1 on 2019-10-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='house_roles',
            new_name='house_rules',
        ),
    ]
