# Generated by Django 3.0b1 on 2019-11-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20191103_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomType',
            new_name='room_type',
        ),
    ]
